### ISSUE TITLE
Add webview modal with list of onramp webservices

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status#57]
# Feature Issue

### User Story
- As a user of Status, I want to see all options to buy crypto, regardless of whether they are dapps or not, because I want to find the option that is most convenient for my context (payment options, KYC limits, etc)
- As a user I want to see all options to buy crypto in a focused modal without distractions of the browser, because this helps me choose and continue
- As a user visiting dap.ps I want to trust that all applications I find there, are decentralized to some extend and meet the [dapp store requirements](https://status.im/developer_tools/run_on_status/dapp_store_requirements.html)

### Impact
1)  How will this get more people to use Status more often?
Make it easy for people to obtain and hold crypto in their Status wallet, making the application hold value to return to
2)  How will this drive SNT revenue?
In time we can offer a more integrated service in exchange of a fee

### Description
[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: 
Add webview modal to open url of a page that shows a list of (decentralized) webapplications to buy crypto 
- Tap on banner in Wallet (https://github.com/status-im/status-react/pull/11530)
- Open webview modal with list of webservices
- Tap on webservice opens service in browser

WIP on [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=10680%3A39976) 

### Acceptance Criteria
[comment]: # (Rules for the future PR to be accepted.)
List of webservices shown in modal is preloaded and shown without delay

### Notes
Currently, the banner points to https://dap.ps/discover-dapps/categories/CRYPTO_ONRAMPS this limits the number of options the user has as it only includes dapps. Webservices included in list are to be defined:
- Wyre
- Moonpay
- Changelly
- Transak
- Ramp.network
- Local Cryptos
- Settle network 
- Simplex
- Xanpool

Webview modal should also be used for Need help? > FAQ and About > Privacy policy

@j-zerah, can you please review and add this issue to the agenda to discuss on our next buy crypto call?

**Comment by hesterbruikman** [comment]
@guylouis looks like this issue can be closed. Any objections?

**Comment by guylouis** [comment]
indeed
