### ISSUE TITLE
Enable Link Preview / URL Unfurling for our.status.im

### ISSUE THREAD

**Issue by j-zerah** [status-im/status#60]
enable link preview so when we post Status blogs into the public channels, the imagery appears in the chat UI.

This will help our own content stand out more in the app

@cammellos @guylouis

**Comment by AK47Status** [comment]
Could we include Reddit and Medium, too?

**Comment by j-zerah** [comment]
@guylouis @cammellos with some upcoming campaigns and work on the bots, can we try to get these link previews in the next release?

**Comment by cammellos** [comment]
We can probably schedule it for 1.12, 1.11 is about to be cut.

**Comment by j-zerah** [comment]
Ok - but these issues along with https://github.com/status-im/status/issues/49 were raised before 1.10 even so not sure the best process to get these marketing centric features included in releases. They will help us out a lot. 

cc @guylouis

**Comment by cammellos** [comment]
Provided the implementation is simple I can add them on the backlog and we can squeeze them in the release scheduled for when they are ready, would that be ok?

**Comment by j-zerah** [comment]
yes of course thank you! Perhaps I am just unaware of level of effort for implementation per domain. These are low hanging fruit. Ill work with the marketing team to define a future list of potential domains so it is not piecemeal moving forward.

**Comment by cammellos** [comment]
This one is included in 1.12, closing as already merged in develop
